{% set version = "2.0.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: aa8f0fda988353f37831356d82aadafa4b44815d3c4daadcda046f0f345567ce

build:
  number: 1000
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj4 =6.0.*
  run:
    - python
    - proj4 =6.0.*

test:
  imports:
    - pyproj

about:
  home: https://github.com/jswhit/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
