{% set version = "3.3.0" %}
# `setup.py` requires `proj >=8.0.0`, but s we don't test against it
# and - other than `8.0.1` in `linux-64` - we ONLY have `8.2.1` in our
# repo.
{% set proj_min = "8.2.1" %}


package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: ce8bfbc212729e9a643f5f5d77f7a93394e032eda1e2d8799ae902d08add747e

build:
  number: 0
  skip: true  # [py<38]
  skip: true  # [win32] proj dependency isn't built for win32 right now.
  entry_points:
    - pyproj=pyproj.__main__:main
  script:
    - export "PROJ_VERSION={{ proj }}"  # [unix]
    - set "PROJ_VERSION={{ proj }}"     # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.28.4
    - proj >={{ proj_min }}
  run:
    - python
    - proj >={{ proj_min }}
    - certifi

test:
  # NOTE to future maintainers: Reenable full testing when pandas is available for python 3.10.
  source_files:
    - test
  requires:
    - pytest
    - shapely  # [(not osx or py<=39) and (not s390x)]
    - numpy
    - pandas  # [py<310 or osx]  Not available for python 3.10 right now for win or lin 64
    - xarray  # [py<310 or osx] Depends on pandas
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - pytest -v -s  # [py<310 or osx]  Disable until pandas is available.

about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library
  dev_url: https://github.com/pyproj4/pyproj
  #doc_url: https://pyproj4.github.io/pyproj/{{ version }}
  #doc_src_url: https://github.com/pyproj4/pyproj/tree/{{ version }}/docs
  doc_url: https://pyproj4.github.io/pyproj/
  doc_src_url: https://github.com/pyproj4/pyproj/tree/main/docs

extra:
  recipe-maintainers:
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
