{% set version = "2.6.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 977542d2f8cf2981cf3ad72cedfebcd6ac56977c7aa830d9b49fa7888b56e83d

build:
  number: 1
  skip: true  # [py<35]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - mock
    - numpy
  imports:
    - pyproj
  commands:
    - pytest -v -s -k "not (test_datum or test_doctests or test_transformer__operations or test_transformer__operations__scope_remarks or test_transformer_group__unavailable or test_transform_group__missing_best or test_transform_group__area_of_interest or test_transformer_group__get_transform_crs or test_transformer__area_of_interest or test_transformer_proj__area_of_interest or test_transformer_equals)"

about:
  home: https://github.com/pyproj4/pyproj
  license: OSI
  license_file: LICENSE
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
