{% set version = "1.9.5.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  git_url: https://github.com/jswhit/pyproj
  git_tag: v{{ version }}rel

build:
  number: 1
  script:
    - del _proj.c  # [win]
    - set "PROJ_DIR=%PREFIX%"  # [win]
    - rm -d _proj.c  # [unix]
    - export PROJ_DIR="${PREFIX}"  # [unix]
    - export CFLAGS="${CFLAGS} -Wno-strict-prototypes -Wdeprecated-declarations"  # [win]
    - cythonize -a -i _proj.pyx
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - proj4
  run:
    - python
    - numpy

test:
  imports:
    - pyproj

about:
  home: https://github.com/jswhit/pyproj
  license: OSI
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
