{% set name = "pyproj" %}
{% set version = "3.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39a0cf1ecc7e282d1d30f36594ebd55c9fae1fda8a2622cee5d100430628f88c

build:
  number: 0
  skip: true  # [py<311]
  script_env:
    - PROJ_VERSION={{ proj }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pyproj=pyproj.__main__:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=3.1
    - proj {{ proj }}
    - setuptools >=61.0.0
    - wheel
  run:
    - python
    - certifi
    - proj # bounds through run_exports.

# Assertion errors
{% set deselect_tests = " --deselect=test/crs/test_crs.py::test_datum_horizontal" %}
{% set deselect_tests = deselect_tests + " --deselect=test/crs/test_crs.py::test_sub_crs" %}

test:
  source_files:
    - test
    - pytest.ini
  # Imports are in run_test.py
  #imports:
    #- pyproj
  requires:
    - packaging
    - pytest
    - numpy
    - pandas
    - shapely
    - xarray
    - pip
  commands:
    - pip check
    - pyproj --verbose
    - pyproj --help
    - pytest -v test {{ deselect_tests }}

about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library
  description: |
    Python interface to PROJ (cartographic projections and coordinate transformations library).
  dev_url: https://github.com/pyproj4/pyproj
  doc_url: https://pyproj4.github.io/pyproj/stable

extra:
  recipe-maintainers:
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
