{% set version = "2.2.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: ec89e68a0cf210af0cc2724b5f8601d4b6809ff0f556e16efc8c955e79672f7a

build:
  number: 0
  skip: True  # [win and vc<14]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj4
  run:
    - python
    - proj4
    - aenum  # [py<36]

test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
