{% set version = "3.6.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 44aa7c704c2b7d8fb3d483bbf75af6cb2350d30a63b144279a09b75fead501bf

build:
  number: 1
  skip: true  # [py<39]
  script_env:
    - PROJ_VERSION={{ proj }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pyproj=pyproj.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=3
    - pip
    - proj {{ proj }}
    - setuptools
    - wheel
  run:
    - python
    - certifi
    - proj # bounds through run_exports.

test:
  source_files:
    - test
    - pytest.ini
  # Imports are in run_test.py
  #imports:
    #- pyproj
  requires:
    - packaging
    - pytest
    - numpy
    - pandas
    - shapely # [not s390x]
    - xarray
    - pip
  commands:
    - pip check
    - pyproj --verbose
    - pyproj --help
    - pytest -v -s -m "not network" -m "not slow"

about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library
  description: |
    Python interface to PROJ (cartographic projections and coordinate transformations library).
  dev_url: https://github.com/pyproj4/pyproj
  doc_url: https://pyproj4.github.io/pyproj/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
