{% set version = "2.2.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 0a4f793cc93539c2292638c498e24422a2ec4b25cb47545addea07724b2a56e5

build:
  number: 0
  skip: True  # [win and vc<14]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj4
  run:
    - python
    - proj4

test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
