{% set version = "2.1.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: ac6176ba67e9184bb77748f2b31650d9a72ddf45beb1575555abe8160935964d

build:
  number: 0
  skip: True  # [win and vc<14]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj4 6.0.0
  run:
    - python
    - proj4 6.0.0

test:
  imports:
    - pyproj

about:
  home: https://github.com/jswhit/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
