{% set version = "2.4.2.post1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 1da7f86d3b5e80ba3dabfd2c904a41bb6997ad9b55b47a934035492eaa0f331e
  patches:
    - 0001-proj-6.3.0-tests.patch

build:
  number: 1
  skip: True  # [py<35]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - mock
    - numpy
  imports:
    - pyproj
  commands:
    - pytest -v -s

about:
  home: https://github.com/pyproj4/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
