{% set version = "3.4.1" %}
# `setup.py` requires `proj >=8.0.0`, but s we don't test against it
# and - other than `8.0.1` in `linux-64` - we ONLY have `8.2.1` in our
# repo.
{% set proj_min = "8.2.1" %}


package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 261eb29b1d55b1eb7f336127344d9b31284d950a9446d1e0d1c2411f7dd8e3ac

build:
  number: 0
  skip: true  # [py<38]
  script_env:
    - PROJ_VERSION={{ proj }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyproj=pyproj.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - proj ={{ proj_min }}
    - setuptools
    - wheel
  run:
    - python
    - certifi
    - proj >={{ proj_min }}

test:
  source_files:
    - test
  # Imports are in run_test.py
  #imports:
    #- pyproj
  requires:
    - pytest
    - shapely  # [not s390x]
    - numpy
    - pandas
    - xarray
    - pip
  commands:
    - pip check
    - pyproj --verbose
    - pyproj --help
    # Skip tests that fail with AccertionError:
    - pytest -v -s -k "not (test_get_transform_grid_list__bbox__antimeridian or test_get_transform_grid_list__bbox__out_of_bounds)"

about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library
  description: |
    Python interface to PROJ (cartographic projections and coordinate transformations library).
  dev_url: https://github.com/pyproj4/pyproj
  doc_url: https://pyproj4.github.io/pyproj/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
