# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vM7QE/PFMWYPco4Gfcq+cbpTCbkBWsa+WEiwe16u4goGVe/RuOEdAxQJVDopiNv6IQk8CDVZSwclBTm4drUtQy3H20ed1q1EzLfwEFdtcMoa9Gj5hTFEITwSBMHT5EMawTBzRe41VQsS6PhyyYAm6e16Yck/KlIl5LI95ZD0XsHvP0Tb61AP9LYpaLQsMzQMHAzde/qFq2i/67KLeNJpt2fMpQ8wtZgjLfee953NKLGLL8ASaZI98A1ytyxW+auz0cZ0Q52DA7Nzx3+Vn8DpAFjMbCQlXkONaugNWAs0lCZwosHGWylHx6KVnWDqYZPBPfTGVvS6gz+61l6fCtVThcIjgq9jPqtmerI2e/oXdsMPyAAaGbcd7zBQsN8l5qqNKVwzShOVbaRhBuh4nlUH6IG7mDVbjffbUV2daIsZioRHn9NHBeUA0VdOky4wt2udgTa8aiRLp+iv1zMmhNt22bOYZjxQMhopbz0FDh3bkxHBSqieLw9EPVNoz1bVEHko3A2F4GhKSNlzMIyxY+rBJsZkTNuYUUHBCZfKyS/RA+zVbpTXg7uCJli1KZ0I6dexmb1unUitrR65BTZMM/9h36aktDTjK2l0sa2RjhvQvEfslNpdarztmg5qmL39iKLuNFlpae0bb3hGceshDxy+kLuxFhAuyYx8nmZ798E7ufc="


before install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
