travis:
  secure:
    BINSTAR_TOKEN: dc2Dn8mwc7y1Br67GGf/RoEG2UU7QCYTsrflmjN5FihIjDja58LDEU2TvxN4pBchyxJpEdoeI66/mM6mDtGAVpQF472ZEnb7rNhKJjGCqkWxn262aHPNE6xz4e+Gga0cNv1oResqCaObw373v74Qj6J8hev8wZZXac9maozwU3DGFH0JAr3FYh62lRaQQUcWi59rcBbjgOFFKobzCKixgCOKVHXVeBC+nGwOZPKt7XidIZe70C7/DyMhsELRQQiE9peepRlpAl6S8wQEzav/J/BU46VnSPJeHOEawQDh799SzexUGutDnBtoozUuuSrerQ4UuOWP6/Xm4zt0zcTABkIT0AmIi3U0vtJDcA1ulbOW2Kd+pNVNx4V2acBjyY4J+C0/sAlJHw/V8MhAJA0DeB5o8JuYQWiu89eGOHrUbMKJ7vdNAVDjtha+jCcA/+Uwe+u3NjRtpNGM5HeY8g4Y0/mHqbL5VU5y82WBsjA2UTKwSEP9n5oc5d1xZeJY5vmjoOVZ9eakNg2PxVDAbL1Ueft3uumUySBrdvFdO4pQNSx4PSHeoo3bmbQtUZk/xbcMw/7L1ik4Du89nXYnQSNCP643uL5XI3EHe7DH7E7uJ3cw3hpHnrcrQAZI+0amiW95wBYYS3Bx9CNNkaCdlcd0iZPpxtdGqyxzR9GcytahJdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
